// Generated by gencpp from file jetbot_mini/State_msg.msg
// DO NOT EDIT!


#ifndef JETBOT_MINI_MESSAGE_STATE_MSG_H
#define JETBOT_MINI_MESSAGE_STATE_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jetbot_mini
{
template <class ContainerAllocator>
struct State_msg_
{
  typedef State_msg_<ContainerAllocator> Type;

  State_msg_()
    : index(0)
    , ready(false)  {
    }
  State_msg_(const ContainerAllocator& _alloc)
    : index(0)
    , ready(false)  {
  (void)_alloc;
    }



   typedef int32_t _index_type;
  _index_type index;

   typedef uint8_t _ready_type;
  _ready_type ready;





  typedef boost::shared_ptr< ::jetbot_mini::State_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jetbot_mini::State_msg_<ContainerAllocator> const> ConstPtr;

}; // struct State_msg_

typedef ::jetbot_mini::State_msg_<std::allocator<void> > State_msg;

typedef boost::shared_ptr< ::jetbot_mini::State_msg > State_msgPtr;
typedef boost::shared_ptr< ::jetbot_mini::State_msg const> State_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jetbot_mini::State_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jetbot_mini::State_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jetbot_mini::State_msg_<ContainerAllocator1> & lhs, const ::jetbot_mini::State_msg_<ContainerAllocator2> & rhs)
{
  return lhs.index == rhs.index &&
    lhs.ready == rhs.ready;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jetbot_mini::State_msg_<ContainerAllocator1> & lhs, const ::jetbot_mini::State_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jetbot_mini

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jetbot_mini::State_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jetbot_mini::State_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetbot_mini::State_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetbot_mini::State_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetbot_mini::State_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetbot_mini::State_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jetbot_mini::State_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d2833016bdbb0ca11d012b3bd7a19bf";
  }

  static const char* value(const ::jetbot_mini::State_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d2833016bdbb0caULL;
  static const uint64_t static_value2 = 0x11d012b3bd7a19bfULL;
};

template<class ContainerAllocator>
struct DataType< ::jetbot_mini::State_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jetbot_mini/State_msg";
  }

  static const char* value(const ::jetbot_mini::State_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jetbot_mini::State_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 index\n"
"bool ready\n"
;
  }

  static const char* value(const ::jetbot_mini::State_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jetbot_mini::State_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
      stream.next(m.ready);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct State_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jetbot_mini::State_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jetbot_mini::State_msg_<ContainerAllocator>& v)
  {
    s << indent << "index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.index);
    s << indent << "ready: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ready);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETBOT_MINI_MESSAGE_STATE_MSG_H
