// Generated by gencpp from file jetbot_mini/Time_step_msg.msg
// DO NOT EDIT!


#ifndef JETBOT_MINI_MESSAGE_TIME_STEP_MSG_H
#define JETBOT_MINI_MESSAGE_TIME_STEP_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jetbot_mini
{
template <class ContainerAllocator>
struct Time_step_msg_
{
  typedef Time_step_msg_<ContainerAllocator> Type;

  Time_step_msg_()
    : time_step(0)  {
    }
  Time_step_msg_(const ContainerAllocator& _alloc)
    : time_step(0)  {
  (void)_alloc;
    }



   typedef int64_t _time_step_type;
  _time_step_type time_step;





  typedef boost::shared_ptr< ::jetbot_mini::Time_step_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jetbot_mini::Time_step_msg_<ContainerAllocator> const> ConstPtr;

}; // struct Time_step_msg_

typedef ::jetbot_mini::Time_step_msg_<std::allocator<void> > Time_step_msg;

typedef boost::shared_ptr< ::jetbot_mini::Time_step_msg > Time_step_msgPtr;
typedef boost::shared_ptr< ::jetbot_mini::Time_step_msg const> Time_step_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jetbot_mini::Time_step_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jetbot_mini::Time_step_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jetbot_mini::Time_step_msg_<ContainerAllocator1> & lhs, const ::jetbot_mini::Time_step_msg_<ContainerAllocator2> & rhs)
{
  return lhs.time_step == rhs.time_step;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jetbot_mini::Time_step_msg_<ContainerAllocator1> & lhs, const ::jetbot_mini::Time_step_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jetbot_mini

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jetbot_mini::Time_step_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jetbot_mini::Time_step_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetbot_mini::Time_step_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetbot_mini::Time_step_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetbot_mini::Time_step_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetbot_mini::Time_step_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jetbot_mini::Time_step_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "46804f01808531bde26c16e8419d8a77";
  }

  static const char* value(const ::jetbot_mini::Time_step_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x46804f01808531bdULL;
  static const uint64_t static_value2 = 0xe26c16e8419d8a77ULL;
};

template<class ContainerAllocator>
struct DataType< ::jetbot_mini::Time_step_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jetbot_mini/Time_step_msg";
  }

  static const char* value(const ::jetbot_mini::Time_step_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jetbot_mini::Time_step_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 time_step\n"
;
  }

  static const char* value(const ::jetbot_mini::Time_step_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jetbot_mini::Time_step_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time_step);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Time_step_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jetbot_mini::Time_step_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jetbot_mini::Time_step_msg_<ContainerAllocator>& v)
  {
    s << indent << "time_step: ";
    Printer<int64_t>::stream(s, indent + "  ", v.time_step);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETBOT_MINI_MESSAGE_TIME_STEP_MSG_H
